# Generated by Django 2.2.7 on 2019-11-06 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='업체명')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('description', models.TextField(verbose_name='상세소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='메뉴사진')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴이름')),
                ('price', models.PositiveIntegerField(verbose_name='메뉴가격')),
                ('category', models.CharField(choices=[('KF', 'Korean_Food'), ('JF', 'Japanese_Food'), ('CF', 'Chines_Food '), ('IF', 'Italian_Food'), ('FF', 'French_Food'), ('TF', 'Thai_Food'), ('VF', 'Vietnamese_Food')], default='KF', max_length=2)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
            ],
        ),
    ]
